"""
Shared helpers for AetherState reference-dataset generation.

This module contains only pure, lightweight utilities for parsing the
aetherstate_bundle.py architecture dict and computing the binary record layout.
It intentionally avoids importing PyTorch or other heavy dependencies so that
the reference-data generation scripts can load it quickly.
"""

from __future__ import annotations

import ast
from pathlib import Path

REQUIRED_ARCHITECTURE_KEYS = {
    # Keys that the evaluator/training-record format truly needs.  Everything
    # else (accumulator_size, hidden_size, quant_shift, etc.) is part of the
    # mutable DFCAM topology and may be added/removed/renamed by the LLM.
    "input_features",
    "output_slots",
    "move_stride",
    "max_features_per_record",
    "weight_magic",
    "weight_version",
}

# Legacy defaults for the original DFCAM seed.  When the LLM omits a topology
# key, the injected C++/Python constants fall back to these values so the seed
# still compiles and runs.  This lets the LLM invent new architectures without
# being forced to keep every legacy key.
DEFAULT_ARCHITECTURE = {
    "input_features": 768,
    "accumulator_size": 256,
    "hidden_size": 32,
    "output_slots": 4096,
    "move_stride": 64,
    "quant_shift": 7,
    "weight_magic": "AESTATEW",
    "max_features_per_record": 32,
    "weight_version": 1,
}


def parse_bundle_architecture(bundle_path: Path) -> dict:
    """Return the ARCHITECTURE dict from an aetherstate_bundle.py file.

    Raises ValueError if the file is malformed or the dict is missing.
    The bundle is parsed with ast.literal_eval; it is never executed.
    """
    if not bundle_path.is_file():
        raise ValueError(f"Bundle not found: {bundle_path}")

    source = bundle_path.read_text(encoding="utf-8")
    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        raise ValueError(f"Bundle syntax error: {e}") from e

    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id == "ARCHITECTURE":
                    try:
                        architecture = ast.literal_eval(node.value)
                    except ValueError as exc:
                        raise ValueError("ARCHITECTURE is not a literal dict") from exc
                    if not isinstance(architecture, dict):
                        raise ValueError("ARCHITECTURE must be a dict")
                    missing = REQUIRED_ARCHITECTURE_KEYS - set(architecture.keys())
                    if missing:
                        raise ValueError(
                            f"ARCHITECTURE is missing required keys: {sorted(missing)}"
                        )
                    # Merge with legacy defaults so the C++/Python injection has
                    # sensible fallbacks for keys the LLM chose not to specify.
                    merged = DEFAULT_ARCHITECTURE.copy()
                    merged.update(architecture)
                    return merged

    raise ValueError("ARCHITECTURE dict not found in bundle")


def training_record_size(architecture: dict) -> int:
    """Return the byte size of a single TrainingRecord.

    The C++ struct is:
        int32_t side_to_move;
        int32_t n_features;
        int32_t features[max_features_per_record];
        int32_t from;
        int32_t to;
        int32_t promo;
        int32_t outcome;
    """
    max_features = architecture["max_features_per_record"]
    return 4 + 4 + 4 * max_features + 4 + 4 + 4 + 4


def build_cpp_architecture_header(architecture: dict) -> str:
    """Return the block of #define macros injected before seed_engine.cpp.

    Every key in the merged architecture is injected as a macro so the LLM can
    add custom keys (e.g.  num_heads, num_layers) and use them in the C++ code.
    """
    merged = DEFAULT_ARCHITECTURE.copy()
    merged.update(architecture)
    lines = ["// Auto-generated by AetherState reference-data tools. Do not edit by hand."]
    for key, value in merged.items():
        # Skip the weight magic; that is handled separately as a byte header.
        if key == "weight_magic":
            continue
        # Skip string values in C++ macros to avoid emitting broken bare tokens.
        # Custom numeric keys are injected; string keys are left for Python only.
        if isinstance(value, str):
            continue
        macro_name = key.upper()
        lines.append(f"#define {macro_name} {value}")
    return "\n".join(lines) + "\n"


def build_python_arch_constants(architecture: dict) -> str:
    """Return the contents of arch_constants.py used by train_loop.py.

    Every key in the merged architecture is emitted as a Python constant so
    the LLM can add custom keys (e.g.  num_heads, num_layers) and use them in
    the training code.
    """
    merged = DEFAULT_ARCHITECTURE.copy()
    merged.update(architecture)
    max_features = merged["max_features_per_record"]
    weight_magic = merged["weight_magic"]

    constant_lines = []
    for key, value in merged.items():
        if key == "weight_magic":
            constant_lines.append(f'{key.upper()} = {value!r}.encode("ascii")')
        elif isinstance(value, str):
            constant_lines.append(f"{key.upper()} = {value!r}")
        else:
            constant_lines.append(f"{key.upper()} = {value!r}")

    constants_body = "\n".join(constant_lines)

    return f"""# Auto-generated by AetherState reference-data tools. Do not edit by hand.
{constants_body}
# NET_SIZE intentionally removed: topology is mutable. Python exporter and C++ loader must agree.

import numpy as np
TRAINING_RECORD_DTYPE = np.dtype([
    ("side_to_move", "<i4"),
    ("n_features", "<i4"),
    ("features", "<i4", {max_features}),
    ("from_", "<i4"),
    ("to_", "<i4"),
    ("promo", "<i4"),
    ("outcome", "<i4"),
])
"""


def validate_dataset(path: Path, architecture: dict, min_records: int = 100) -> int:
    """Validate that a reference dataset is aligned and non-trivial.

    Returns the number of records. Raises ValueError on misalignment or
    an empty dataset.
    """
    if not path.is_file():
        raise ValueError(f"Dataset not found: {path}")

    data = path.read_bytes()
    rec_size = training_record_size(architecture)
    if len(data) < rec_size:
        raise ValueError(
            f"Dataset too small ({len(data)} bytes) for a single {rec_size}-byte record"
        )
    if len(data) % rec_size != 0:
        raise ValueError(
            f"Dataset size {len(data)} is not a multiple of record size {rec_size}. "
            "The binary may be corrupted or generated with mismatched architecture."
        )

    n_records = len(data) // rec_size
    if n_records < min_records:
        raise ValueError(
            f"Dataset has only {n_records} records, need at least {min_records}"
        )
    return n_records
